// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfDUdU1PF6mhSmm1ht-NDQgUHCT9hVW8',
    appId: '1:292141038283:web:6768e7008d206e2130b94e',
    messagingSenderId: '292141038283',
    projectId: 'velora-vlab',
    authDomain: 'velora-vlab.firebaseapp.com',
    storageBucket: 'velora-vlab.firebasestorage.app',
    measurementId: 'G-05786E0JX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKd1qsUAyg5JQuiELWUOlBtjRWJVEcWqc',
    appId: '1:292141038283:android:453e44c7477def5430b94e',
    messagingSenderId: '292141038283',
    projectId: 'velora-vlab',
    storageBucket: 'velora-vlab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHldVcc41Thz13JzKZ2C1wbmdlZS2hWI',
    appId: '1:292141038283:ios:61172020fbb02c1030b94e',
    messagingSenderId: '292141038283',
    projectId: 'velora-vlab',
    storageBucket: 'velora-vlab.firebasestorage.app',
    androidClientId:
        '292141038283-ua7p2rc6cvogimi84q1gd2o1cshu7kam.apps.googleusercontent.com',
    iosClientId:
        '292141038283-7joo103emh0d9126upk1rks45m7qk14q.apps.googleusercontent.com',
    iosBundleId: 'com.example.velora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHldVcc41Thz13JzKZ2C1wbmdlZS2hWI',
    appId: '1:292141038283:ios:61172020fbb02c1030b94e',
    messagingSenderId: '292141038283',
    projectId: 'velora-vlab',
    storageBucket: 'velora-vlab.firebasestorage.app',
    androidClientId:
        '292141038283-ua7p2rc6cvogimi84q1gd2o1cshu7kam.apps.googleusercontent.com',
    iosClientId:
        '292141038283-7joo103emh0d9126upk1rks45m7qk14q.apps.googleusercontent.com',
    iosBundleId: 'com.example.velora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKfDUdU1PF6mhSmm1ht-NDQgUHCT9hVW8',
    appId: '1:292141038283:web:1f8dcf2583535e8830b94e',
    messagingSenderId: '292141038283',
    projectId: 'velora-vlab',
    authDomain: 'velora-vlab.firebaseapp.com',
    storageBucket: 'velora-vlab.firebasestorage.app',
    measurementId: 'G-6745P1W1XR',
  );
}
